### ISSUE TITLE
访问不了 ： https://raw.githubusercontent.com/xiaomi-passport/maven-repository/master/releases

### ISSUE THREAD

**Issue by songshuilin** [xiaomi-passport/oauth-android-sdk#24]
maven { url 'https://raw.githubusercontent.com/xiaomi-passport/maven-repository/master/releases' }

这个https://raw.githubusercontent.com/xiaomi-passport/maven-repository/master/releases 有问题，访问不了。 导致依赖的时候一直卡住。

**Comment by eggfly** [comment]
试试 maven { url 'https://gitlab.com/xiaomi-passport/maven-repository/raw/master/releases' } raw.githubusercontent.com 可能是已经被GFW了
