### ISSUE TITLE
有关 com.xiaomi.account.ui.AuthorizeActivity 的错误【紧急】

### ISSUE THREAD

**Issue by hanxk** [xiaomi-passport/oauth-android-sdk#7]
类：ComponentInfo{com.xiaomi.account/com.xiaomi.account.ui.AuthorizeActivity}

报错：
1. ClassNotFoundException when unmarshalling: com.xiaomi.account.XiaomiOAuthResponse
2. Method threw 'java.lang.OutOfMemoryError' exception.

请问你们传入AuthorizeActivity 中的 bundle数据是不是有错？调用intent任何相关的方法都会报错。

**Comment by Moonant** [comment]
检查一下 jar 包的版本，和有没有混淆 Parcelable 类
